{
    "name": "Module Data Commom",
    "author": "Zervi",
    "website": "https://www.globalzervi.com",
    "support": "support@zervi.com",
    "category": "Datamodel",
    "summary": """ Data Models""",
    "license": "LGPL-3",
    "version": "19.0.0.0",
    "description": """ Data Models """,
    "depends": [],
    "data": [],
    "installable": True,
    "auto_install": False,
    "application": False,
    "images": [],
}
