{
    'name': 'Purchase Create Vendor Bill',
    'version': '19.0.1.0.0',
    'sequence': 100,
    'summary': 'Restore Create Vendor Bill functionality with smart purchase method detection',
    'category': 'Purchase',
    'author': 'hamzbond',
    'website': 'https://hamzbond.github.io',
    'license': 'LGPL-3',
    'price': 0.00,
    'currency': 'USD',
    'images': [
        'static/description/banner.png',
        'static/description/screenshot_create_bill_button.png',
        'static/description/screenshot_wizard.png',
        'static/description/screenshot_vendor_bill.png',
    ],
    'depends': [
        'purchase',
        'account',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/purchase_order_views.xml',
        'wizards/purchase_bill_wizard_views.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'auto_install': False,
    'application': False,
    'support': 'hamzbond@gmail.com',
}